### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Simnol** [Tiki-God/flo#1]
Raspberry Pi

---

[adam@testbed flo]$ make
gcc -std=c99 -Wall -pedantic -O2 -D_GNU_SOURCE -fstack-protector -fno-exceptions -Wformat-security -Werror   -c -o lookup.o lookup.c
lookup.c: In function 'lookup_ema':
lookup.c:47:52: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'long long unsigned int' [-Werror=format=]
   fprintf(stderr, "DEBUG:: x %f :: y %f :: delta %ld :: alpha %f :: avg %u :: pkts %u\n",
                                                    ^
cc1: all warnings being treated as errors
make: *** [<builtin>: lookup.o] Error 1

---

Potential solution:

lookup.c

  double alpha, y, x;
  uint64_t new_ms, old_ms;
  long int delta;

**Comment by Tiki-God** [comment]
The problem is dependant on 32bit vs 64bit CPU arch.  in stdint.h on 32bit uint64_t is unsigned long long int.  On 64bit it's unsigned long int.  It seems that PRIu64, defined in inttypes.h, is part of C99 for correctly printing uint64_t.

**Comment by Tiki-God** [comment]
Commit bace1cdf4b654515edd8d597a362096ee6de4f52 should hopefully fix this.
